backend:
  name: github
  repo: AmazingWeirdoGuy/ISB-Medsociety-Club-Website
  branch: main
  base_url: /
  auth_endpoint: api/auth

media_folder: "client/public/content/media"
public_folder: "/content/media"

collections:
  - name: "member_classes"
    label: "Member Classes"
    folder: "client/public/content/member-classes"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Display Order", name: "displayOrder", widget: "number", default: 0}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}

  - name: "members"
    label: "Members"
    folder: "client/public/content/members"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Member Class ID", name: "memberClassId", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text", required: false}
      - {label: "Image (Base64 or URL)", name: "image", widget: "text", required: false}
      - {label: "Thumbnail (Base64 or URL)", name: "thumbnail", widget: "text", required: false}
      - {label: "LinkedIn URL", name: "linkedIn", widget: "string", required: false}
      - {label: "Year/Grade", name: "year", widget: "string", required: false}
      - {label: "Display Order", name: "displayOrder", widget: "number", default: 0}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}

  - name: "hero_images"
    label: "Hero Images"
    folder: "client/public/content/hero-images"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Image URL", name: "imageUrl", widget: "string"}
      - {label: "Alt Text", name: "altText", widget: "string"}
      - {label: "Display Order", name: "displayOrder", widget: "number", default: 0}
      - {label: "Active", name: "isActive", widget: "boolean", default: true}

  - name: "news"
    label: "News"
    folder: "client/public/content/news"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown", required: false}
      - {label: "Image (Base64 or URL)", name: "image", widget: "text"}
      - {label: "Published", name: "isPublished", widget: "boolean", default: false}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", required: false}

  - name: "programs"
    label: "Programs"
    folder: "client/public/content/programs"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image (Base64 or URL)", name: "image", widget: "text"}
